version: '3.8'
services:
  samantacampaign:
    build:
      context: .
    container_name: samantacampaign
    restart: always
    command: npm run dev

    ports:
      - 8005:8005
    expose:
      - "8005"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
networks:
  default:
    external: true
    name: webnet